---
- hosts: all
  remote_user: root
  become: true
  vars_files:
  - defaults/main.yml
  vars:
    domain: php-test.dev
    storage_dir: storage
  roles:
  - role: bbatsche.Nginx
    site_type: php
  tasks:
  - include: tasks/main.yml
  handlers:
  - include: handlers/main.yml
  - name: Restart FPM
    service: name=php5-fpm state=restarted
    become: true
