---
- hosts: all
  remote_user: vagrant
  become: yes

  vars:
    console_user: vagrant

  roles:
    - bbatsche.Base

  tasks:
  - name: Always Expand Bash Aliases
    copy:
      content: shopt -s expand_aliases;
      dest: /etc/profile.d/alias.sh
