require_relative "lib/ansible_helper"
require_relative "bootstrap"

RSpec.configure do |config|
  config.before :suite do
    AnsibleHelper.instance.playbook("playbooks/php-playbook.yml", {
      copy_index_php: true,
      copy_favicon: true,
      env_name: "prod"
    })
  end
end

describe command("php --version") do
  it "has no errors" do
    expect(subject.stderr).to eq ''
    expect(subject.exit_status).to eq 0
  end
end

describe command(%Q{php -r 'echo "PHP is running\\n";'}) do
  it "executes PHP code" do
    expect(subject.stdout).to match /^PHP is running$/
  end
end

describe command("php -i") do
  it "does not have XDebug installed" do
    expect(subject.stdout).to_not match /^xdebug support => enabled/
  end
end

describe command("phpunit --version") do
  it "is not installed" do
    expect(subject.stderr).to match /phpunit: command not found/

    expect(subject.exit_status).to_not eq 0
  end
end

describe command("psysh --version") do
  it "is not installed" do
    expect(subject.stderr).to match /psysh: command not found/

    expect(subject.exit_status).to_not eq 0
  end
end

describe command("curl -i php-test.dev") do
  it "sends a 200 OK response" do
    expect(subject.stdout).to match /^HTTP\/1\.1 200 OK$/
  end

  it "executes PHP code" do
    expect(subject.stdout).to match /<title>phpinfo\(\)<\/title>/ # title tag is generated by phpinfo()
  end

  it "does not have XDebug enabled" do
    expect(subject.stdout).to_not match /<th>xdebug support<\/th><th>enabled<\/th>/
  end
end

describe "Nginx config is valid" do
  include_examples "nginx::config"
end
